
name: Build and Push Docker Images to AWS ECR

on:
  push:
    branches:
      - main 
    paths:
      - 'cart/**'
      - 'catalogue/**'
      - 'dispatch/**'
      - 'payment/**'
      - 'ratings/**'
      - 'shipping/**'
      - 'user/**'
      - 'web/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - cart
          - catalogue
          - dispatch
          - payment
          - ratings
          - shipping
          - user
          - web
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/e-commerce${{ matrix.service }}:latest
